//
//  MunsellSwatchData.swift
//  Student Fieldwork App
//
//  Real swatch data for all 12 Munsell Soil Color Charts, derived from
//  the official Munsell Soil Color Charts (2009 revision / 2010-2013
//  production) using the standard Munsell renotation system (Illuminant C
//  -> Bradford-adapted to D65 -> sRGB), cross-checked against the
//  official chart layouts, hue/value/chroma grids, and printed colour
//  names supplied in the 1994 Munsell Soil Color Charts manual and the
//  2009-revision chart scans.
//
//  Fix note: the 10YR chart's bottom value row is genuinely labelled
//  "2/" on the official chart (not "2.5/" like every other chart here) —
//  verified against the chart's own printed diagram labels.
//
//  Update: 5R, 7.5R, 5Y, the 10Y-5GY "Olive Greens" chart, and both Gley
//  charts (previously algorithmic placeholders) have now been replaced
//  with real renotation-table-derived swatches matching the official
//  chart grids and colour names. No placeholder charts remain.
//

import Foundation

enum SwatchData {

    static let fiveR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#CFC6C5", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#D6C4C2", name: "pinkish white"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#E0C1BE", name: "pink"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#EABDB9", name: "pink"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#B6ABAA", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#BEA9A7", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C7A6A3", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#CFA39F", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#DF9D98", name: "light red"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#EF9590", name: "light red"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#9C9190", name: "reddish gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#A48E8D", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#AD8C89", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B58986", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#C4827E", name: "red"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#D27B77", name: "red"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#827776", name: "reddish gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#8A7573", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#937170", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#9B6E6C", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#AA6865", name: "red"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#B7605E", name: "red"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#6A5D5D", name: "dark reddish gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#725A59", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#7B5756", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#825452", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#8F4D4C", name: "red"),
        MunsellSwatch(value: "4", chroma: "8", hex: "#9C4545", name: "red"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#524444", name: "dark reddish gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#5B4141", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#623E3E", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#693A3B", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "6", hex: "#743335", name: "dark red"),
        MunsellSwatch(value: "2", chroma: "1", hex: "#3A2E2F", name: "reddish black"),
        MunsellSwatch(value: "2", chroma: "2", hex: "#412B2D", name: "very dusky red"),
    ]

    static let sevenPointFiveR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#CFC6C4", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#D6C4C0", name: "pinkish white"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#E2C1BA", name: "pink"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#ECBDB4", name: "pink"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#B6ABA9", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#BFA9A5", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C8A6A0", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#D0A39B", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#E09D90", name: "light red"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#F09685", name: "light red"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#9C918F", name: "reddish gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#A58E8B", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#AE8C86", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B68981", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#C58378", name: "red"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#D27C6D", name: "red"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#827775", name: "reddish gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#8B7571", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#94716D", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#9C6E68", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#AA685E", name: "red"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#B86154", name: "red"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#6A5D5C", name: "dark reddish gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#735A58", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#7B5753", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#82544F", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#8F4E46", name: "red"),
        MunsellSwatch(value: "4", chroma: "8", hex: "#9C463D", name: "red"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#524443", name: "dark reddish gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#5B413F", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#623E3B", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#693B37", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "6", hex: "#74342F", name: "dark red"),
        MunsellSwatch(value: "2", chroma: "1", hex: "#3A2E2E", name: "reddish black"),
        MunsellSwatch(value: "2", chroma: "2", hex: "#412B2B", name: "very dusky red"),
    ]

    static let fiveY: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#CCC8B9", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#D0C8AB", name: "very pale brown"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#D3C89E", name: "pale yellow"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#D6C891", name: "pale yellow"),
        MunsellSwatch(value: "8", chroma: "6", hex: "#DDC876", name: "yellow"),
        MunsellSwatch(value: "8", chroma: "8", hex: "#E2C759", name: "yellow"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#B2ADA0", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#B6AD92", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#B9AD85", name: "pale yellow"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#BCAD78", name: "pale yellow"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#C2AD5D", name: "yellow"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#C7AC40", name: "yellow"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#989386", name: "gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#9B9379", name: "light olive gray"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#9F936D", name: "pale olive"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#A29360", name: "pale olive"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#A89244", name: "olive yellow"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#AD9222", name: "olive yellow"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#7E796D", name: "gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#817961", name: "olive gray"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#857955", name: "olive"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#887948", name: "olive"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#8E782B", name: "olive"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#656054", name: "dark gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#686048", name: "dark olive gray"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#6C5F3D", name: "olive"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#6F5F30", name: "olive"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#4C473E", name: "very dark gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#4F4733", name: "dark olive gray"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#403C32", name: "black"),
        MunsellSwatch(value: "2.5", chroma: "2", hex: "#433B29", name: "black"),
    ]

    /// 10Y-5GY "Olive Greens" chart. Mixes two hue columns (10Y and 5GY)
    /// at chroma /2 and /4 only, per the official chart layout — so each
    /// swatch carries a `hueTag` to keep the notation correct.
    static let oliveGreens: [MunsellSwatch] = [
        // 10Y
        MunsellSwatch(value: "6", chroma: "2", hex: "#969579", name: "light grayish olive", hueTag: "10Y"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#999660", name: "pale olive", hueTag: "10Y"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#7C7B62", name: "grayish olive", hueTag: "10Y"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#7E7C47", name: "light olive", hueTag: "10Y"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#626149", name: "dark grayish olive", hueTag: "10Y"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#656230", name: "olive", hueTag: "10Y"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#4A4934", name: "very dark grayish olive", hueTag: "10Y"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#4B491D", name: "dark olive", hueTag: "10Y"),
        // 5GY
        MunsellSwatch(value: "6", chroma: "2", hex: "#8F977C", name: "light grayish green", hueTag: "5GY"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#8C9966", name: "pale yellowish green", hueTag: "5GY"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#767D65", name: "grayish green", hueTag: "5GY"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#727F50", name: "light olive green", hueTag: "5GY"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#5C634D", name: "dark grayish green", hueTag: "5GY"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#586638", name: "olive green", hueTag: "5GY"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#444A38", name: "very dark grayish green", hueTag: "5GY"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#3F4C24", name: "dark olive green", hueTag: "5GY"),
    ]

    /// Gley 1 chart. Neutral (N) column plus four chromatic hue columns
    /// (10Y, 5GY, 10GY, 5G) at chroma /1, with an extra 5G column at
    /// chroma /2 — matching "MUNSELL COLOR CHART 1 FOR GLEY".
    static let gley1: [MunsellSwatch] = [
        // Neutral (N) column
        MunsellSwatch(value: "8", chroma: "0", hex: "#C8C8C8", name: "white", hueTag: "N"),
        MunsellSwatch(value: "7", chroma: "0", hex: "#ADADAD", name: "light gray", hueTag: "N"),
        MunsellSwatch(value: "6", chroma: "0", hex: "#939393", name: "gray", hueTag: "N"),
        MunsellSwatch(value: "5", chroma: "0", hex: "#797979", name: "gray", hueTag: "N"),
        MunsellSwatch(value: "4", chroma: "0", hex: "#606060", name: "dark gray", hueTag: "N"),
        MunsellSwatch(value: "3", chroma: "0", hex: "#474848", name: "very dark gray", hueTag: "N"),
        MunsellSwatch(value: "2.5", chroma: "0", hex: "#3C3C3C", name: "black", hueTag: "N"),
        // 10Y (chroma /1)
        MunsellSwatch(value: "8", chroma: "1", hex: "#CAC9B9", name: "light greenish gray", hueTag: "10Y"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#AFAE9F", name: "light greenish gray", hueTag: "10Y"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#959486", name: "greenish gray", hueTag: "10Y"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#7B7A6D", name: "greenish gray", hueTag: "10Y"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#616155", name: "dark greenish gray", hueTag: "10Y"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#49483E", name: "very dark greenish gray", hueTag: "10Y"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#3D3C33", name: "greenish black", hueTag: "10Y"),
        // 5GY (chroma /1)
        MunsellSwatch(value: "8", chroma: "1", hex: "#C6CABA", name: "light greenish gray", hueTag: "5GY"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#ACAFA1", name: "light greenish gray", hueTag: "5GY"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#919588", name: "greenish gray", hueTag: "5GY"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#777B6F", name: "greenish gray", hueTag: "5GY"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#5E6257", name: "dark greenish gray", hueTag: "5GY"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#464940", name: "very dark greenish gray", hueTag: "5GY"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#3A3D35", name: "greenish black", hueTag: "5GY"),
        // 10GY (chroma /1)
        MunsellSwatch(value: "8", chroma: "1", hex: "#C0CBBF", name: "light greenish gray", hueTag: "10GY"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A6B0A5", name: "light greenish gray", hueTag: "10GY"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#8C968C", name: "greenish gray", hueTag: "10GY"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#737C73", name: "greenish gray", hueTag: "10GY"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#5A625A", name: "dark greenish gray", hueTag: "10GY"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#424943", name: "very dark greenish gray", hueTag: "10GY"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#373E38", name: "greenish black", hueTag: "10GY"),
        // 5G (chroma /1)
        MunsellSwatch(value: "8", chroma: "1", hex: "#BDCBC3", name: "light greenish gray", hueTag: "5G"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A3B1A9", name: "light greenish gray", hueTag: "5G"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#8A968F", name: "greenish gray", hueTag: "5G"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#717C76", name: "greenish gray", hueTag: "5G"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#58635D", name: "dark greenish gray", hueTag: "5G"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#414A45", name: "very dark greenish gray", hueTag: "5G"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#363E3A", name: "greenish black", hueTag: "5G"),
        // 5G (chroma /2)
        MunsellSwatch(value: "8", chroma: "2", hex: "#B2CFBE", name: "pale green", hueTag: "5G"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#99B4A5", name: "pale green", hueTag: "5G"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#80998C", name: "grayish green", hueTag: "5G"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#687F73", name: "grayish green", hueTag: "5G"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#50655A", name: "dark grayish green", hueTag: "5G"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#394C43", name: "dark grayish green", hueTag: "5G"),
        MunsellSwatch(value: "2.5", chroma: "2", hex: "#2F4038", name: "very dark grayish green", hueTag: "5G"),
    ]

    /// Gley 2 chart. Six hue columns at chroma /1: a greenish-gray family
    /// (10G, 5BG, 10BG) and a bluish-gray family (5B, 10B, 5PB) — matching
    /// "MUNSELL COLOR CHART 2 FOR GLEY".
    static let gley2: [MunsellSwatch] = [
        // 10G
        MunsellSwatch(value: "8", chroma: "1", hex: "#BCCBC6", name: "light greenish gray", hueTag: "10G"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A2B1AC", name: "light greenish gray", hueTag: "10G"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#899692", name: "greenish gray", hueTag: "10G"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#707C78", name: "greenish gray", hueTag: "10G"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#57635F", name: "dark greenish gray", hueTag: "10G"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#404A47", name: "very dark greenish gray", hueTag: "10G"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#353E3B", name: "greenish black", hueTag: "10G"),
        // 5BG
        MunsellSwatch(value: "8", chroma: "1", hex: "#BCCBC8", name: "light greenish gray", hueTag: "5BG"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A2B1AE", name: "light greenish gray", hueTag: "5BG"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#889694", name: "greenish gray", hueTag: "5BG"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#6F7C7B", name: "greenish gray", hueTag: "5BG"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#576261", name: "dark greenish gray", hueTag: "5BG"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#3F4A49", name: "very dark greenish gray", hueTag: "5BG"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#343E3D", name: "greenish black", hueTag: "5BG"),
        // 10BG
        MunsellSwatch(value: "8", chroma: "1", hex: "#BDCBCB", name: "light greenish gray", hueTag: "10BG"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A3B0B0", name: "light greenish gray", hueTag: "10BG"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#899697", name: "greenish gray", hueTag: "10BG"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#707C7D", name: "greenish gray", hueTag: "10BG"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#576263", name: "dark greenish gray", hueTag: "10BG"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#3F4A4B", name: "very dark greenish gray", hueTag: "10BG"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#343E3F", name: "greenish black", hueTag: "10BG"),
        // 5B
        MunsellSwatch(value: "8", chroma: "1", hex: "#BFCACC", name: "light bluish gray", hueTag: "5B"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A5AFB2", name: "light bluish gray", hueTag: "5B"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#8B9598", name: "bluish gray", hueTag: "5B"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#717B7E", name: "bluish gray", hueTag: "5B"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#586265", name: "dark bluish gray", hueTag: "5B"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#3F494D", name: "very dark bluish gray", hueTag: "5B"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#343D41", name: "bluish black", hueTag: "5B"),
        // 10B
        MunsellSwatch(value: "8", chroma: "1", hex: "#C2C9CD", name: "light bluish gray", hueTag: "10B"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#A7AFB3", name: "light bluish gray", hueTag: "10B"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#8D9499", name: "bluish gray", hueTag: "10B"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#737B80", name: "bluish gray", hueTag: "10B"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#5A6166", name: "dark bluish gray", hueTag: "10B"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#41484E", name: "very dark bluish gray", hueTag: "10B"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#363D42", name: "bluish black", hueTag: "10B"),
        // 5PB
        MunsellSwatch(value: "8", chroma: "1", hex: "#C5C8CD", name: "light bluish gray", hueTag: "5PB"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#AAAEB3", name: "light bluish gray", hueTag: "5PB"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#909499", name: "bluish gray", hueTag: "5PB"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#767A80", name: "bluish gray", hueTag: "5PB"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#5D6067", name: "dark bluish gray", hueTag: "5PB"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#44484F", name: "very dark bluish gray", hueTag: "5PB"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#393C43", name: "bluish black", hueTag: "5PB"),
    ]

    static let tenR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#D3C4C7", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#DBC3C3", name: "pinkish white"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#E0BEBC", name: "pink"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#EABBB5", name: "pink"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#BCACAD", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#C4A7A9", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C9A6A2", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#D5A49D", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#DE9A8F", name: "light red"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#E99082", name: "light red"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#A29295", name: "reddish gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#A88B8F", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#AE8887", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B78682", name: "weak red"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#C78179", name: "red"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#CC756B", name: "red"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#857679", name: "reddish gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#8F7777", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#957270", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#9E6D69", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#A86459", name: "red"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#B35C48", name: "red"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#6D5D60", name: "dark reddish gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#785956", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#7F524F", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#824D45", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#8E483E", name: "red"),
        MunsellSwatch(value: "4", chroma: "8", hex: "#993D32", name: "red"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#513F3F", name: "dark reddish gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#5B3C39", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#603733", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#6A3733", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "6", hex: "#742A21", name: "dark red"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#413333", name: "reddish black"),
        MunsellSwatch(value: "2.5", chroma: "2", hex: "#483332", name: "very dusky red"),
    ]

    static let twoPointFiveYR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#D6C6C7", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#D9C4C3", name: "pinkish white"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#E3BEB6", name: "pink"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#E8B9AF", name: "pink"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#B9ADAD", name: "light reddish gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#C6AAA6", name: "pale red"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C9A79E", name: "light reddish brown"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#D1A193", name: "light reddish brown"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#DC9A84", name: "light red"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#E49074", name: "light red"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#A39191", name: "reddish gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#AC8E8C", name: "pale red"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#AF8A82", name: "light reddish brown"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B6857E", name: "light reddish brown"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#C07D6C", name: "red"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#C9785D", name: "red"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#89797A", name: "reddish gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#8D7571", name: "weak red"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#97726C", name: "reddish brown"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#9A6E63", name: "reddish brown"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#A76652", name: "red"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#B15C3D", name: "red"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#6F5D5D", name: "dark reddish gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#765550", name: "weak red"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#7D554D", name: "reddish brown"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#824D45", name: "reddish brown"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#884534", name: "dark red"),
        MunsellSwatch(value: "4", chroma: "8", hex: "#943F2A", name: "dark red"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#4E3C3C", name: "dark reddish gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#583C39", name: "dusky red"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#613A33", name: "dark reddish brown"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#69382A", name: "dark reddish brown"),
        MunsellSwatch(value: "3", chroma: "6", hex: "#6C261E", name: "dark red"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#403434", name: "reddish black"),
        MunsellSwatch(value: "2.5", chroma: "2", hex: "#47322D", name: "very dusky red"),
        MunsellSwatch(value: "2.5", chroma: "3", hex: "#4C2923", name: "dark reddish brown"),
        MunsellSwatch(value: "2.5", chroma: "4", hex: "#562923", name: "dark reddish brown"),
    ]

    static let fiveYR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#D5C5C5", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#DDC1BD", name: "pinkish white"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#DFBFB1", name: "pink"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#E8BDAA", name: "pink"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#BDADAD", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#C5AAA1", name: "pinkish gray"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#CAA595", name: "pinkish gray"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#CDA28F", name: "pinkish gray"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#D99E7E", name: "reddish yellow"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#E0996D", name: "reddish yellow"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#A39393", name: "gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#AB8E88", name: "light reddish brown"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#AA8A80", name: "light reddish brown"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B68879", name: "light reddish brown"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#BE8162", name: "yellowish red"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#C47D4F", name: "yellowish red"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#867878", name: "reddish gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#937871", name: "reddish gray"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#917166", name: "reddish brown"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#956F5C", name: "reddish brown"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#A46846", name: "yellowish red"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#B16031", name: "yellowish red"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#6B5B5B", name: "dark gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#74574F", name: "dark reddish gray"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#7C5344", name: "dark reddish brown"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#7F5040", name: "dark reddish brown"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#85482B", name: "dark reddish brown"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#4E3F3C", name: "very dark gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#523B35", name: "dark reddish brown"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#5A3930", name: "dark reddish brown"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#5D3126", name: "dark reddish brown"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#3F3130", name: "black"),
        MunsellSwatch(value: "2.5", chroma: "2", hex: "#46312C", name: "dark reddish brown"),
    ]

    static let sevenPointFiveYR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#D5C7C4", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#DAC4B9", name: "pinkish white"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#E0C1AD", name: "pink"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#E2BEA6", name: "pink"),
        MunsellSwatch(value: "8", chroma: "6", hex: "#ECBB90", name: "reddish yellow"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#B9AEAC", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#C0AA9D", name: "pinkish gray"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C6A793", name: "pinkish gray"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#CEA48B", name: "light brown"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#D5A076", name: "reddish yellow"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#DA9760", name: "reddish yellow"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#A1928F", name: "gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#AA8F86", name: "pinkish gray"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#AD8C7D", name: "light brown"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B08A73", name: "light brown"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#B9855D", name: "strong brown"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#C77E47", name: "strong brown"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#857979", name: "gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#8B776E", name: "brown"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#937364", name: "brown"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#977359", name: "brown"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#9F6C3F", name: "strong brown"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#A56623", name: "strong brown"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#6A5B58", name: "dark gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#73584D", name: "brown"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#755441", name: "brown"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#7D4F35", name: "brown"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#865129", name: "strong brown"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#50413E", name: "very dark gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#553F31", name: "dark brown"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#573728", name: "dark brown"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#603D29", name: "dark brown"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#3E302D", name: "black"),
        MunsellSwatch(value: "2.5", chroma: "2", hex: "#422F28", name: "very dark brown"),
        MunsellSwatch(value: "2.5", chroma: "3", hex: "#4F3328", name: "very dark brown"),
    ]

    static let tenYR: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#D3C6BE", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#D8C5B7", name: "very pale brown"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#DDC3A8", name: "very pale brown"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#E0C3A3", name: "very pale brown"),
        MunsellSwatch(value: "8", chroma: "6", hex: "#E7BE88", name: "yellow"),
        MunsellSwatch(value: "8", chroma: "8", hex: "#ECBD6F", name: "yellow"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#BBADAA", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#BEAD9D", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C3AB91", name: "pale brown"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#C8A786", name: "pale brown"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#CEA370", name: "brownish yellow"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#D6A058", name: "brownish yellow"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#A0928F", name: "gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#A69082", name: "light brownish gray"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#A88E77", name: "pale brown"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#B08F70", name: "light yellowish brown"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#B78852", name: "brownish yellow"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#BE8737", name: "brownish yellow"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#847977", name: "gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#8A7768", name: "grayish brown"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#90765F", name: "brown"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#937553", name: "yellowish brown"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#9E7035", name: "yellowish brown"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#9D641D", name: "yellowish brown"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#695C54", name: "dark gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#6E5B4C", name: "dark grayish brown"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#75573D", name: "brown"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#795630", name: "dark yellowish brown"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#7F511F", name: "dark yellowish brown"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#493E3C", name: "very dark gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#503E32", name: "very dark grayish brown"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#533626", name: "dark brown"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#644227", name: "dark brown"),
        MunsellSwatch(value: "3", chroma: "6", hex: "#63371C", name: "dark brown"),
        MunsellSwatch(value: "2", chroma: "1", hex: "#332927", name: "black"),
        MunsellSwatch(value: "2", chroma: "2", hex: "#362B27", name: "very dark brown"),
    ]

    static let twoPointFiveY: [MunsellSwatch] = [
        MunsellSwatch(value: "8", chroma: "1", hex: "#D2C8BE", name: "white"),
        MunsellSwatch(value: "8", chroma: "2", hex: "#D8CAB0", name: "pale yellow"),
        MunsellSwatch(value: "8", chroma: "3", hex: "#DBC8A7", name: "pale yellow"),
        MunsellSwatch(value: "8", chroma: "4", hex: "#DCC39A", name: "pale yellow"),
        MunsellSwatch(value: "8", chroma: "6", hex: "#E0C380", name: "yellow"),
        MunsellSwatch(value: "8", chroma: "8", hex: "#E8C068", name: "yellow"),
        MunsellSwatch(value: "7", chroma: "1", hex: "#B9B0AB", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "2", hex: "#BCAF9F", name: "light gray"),
        MunsellSwatch(value: "7", chroma: "3", hex: "#C0AD8D", name: "pale yellow"),
        MunsellSwatch(value: "7", chroma: "4", hex: "#C3AB87", name: "pale yellow"),
        MunsellSwatch(value: "7", chroma: "6", hex: "#CAAB6A", name: "yellow"),
        MunsellSwatch(value: "7", chroma: "8", hex: "#D0A74B", name: "yellow"),
        MunsellSwatch(value: "6", chroma: "1", hex: "#9D938A", name: "gray"),
        MunsellSwatch(value: "6", chroma: "2", hex: "#A9977F", name: "light brownish gray"),
        MunsellSwatch(value: "6", chroma: "3", hex: "#A59178", name: "light yellowish brown"),
        MunsellSwatch(value: "6", chroma: "4", hex: "#AA8D6B", name: "light yellowish brown"),
        MunsellSwatch(value: "6", chroma: "6", hex: "#AC8D4D", name: "olive yellow"),
        MunsellSwatch(value: "6", chroma: "8", hex: "#B68A29", name: "olive yellow"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#847975", name: "gray"),
        MunsellSwatch(value: "5", chroma: "2", hex: "#897969", name: "grayish brown"),
        MunsellSwatch(value: "5", chroma: "3", hex: "#8F7859", name: "light olive brown"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#8E774D", name: "light olive brown"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#967331", name: "light olive brown"),
        MunsellSwatch(value: "4", chroma: "1", hex: "#655C57", name: "dark gray"),
        MunsellSwatch(value: "4", chroma: "2", hex: "#6D5B47", name: "dark grayish brown"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#70593A", name: "olive brown"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#755932", name: "olive brown"),
        MunsellSwatch(value: "3", chroma: "1", hex: "#4D4038", name: "very dark gray"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#4C3F2F", name: "very dark grayish brown"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#4B3925", name: "dark olive brown"),
        MunsellSwatch(value: "2.5", chroma: "1", hex: "#3C3230", name: "black"),
    ]

    /// Common Australian soil colour quick reference. Each entry pairs
    /// a plain-language description with the Munsell code(s) most often
    /// seen for it in the field. All hex values are drawn from the
    /// corresponding full chart's real swatch data above (now that all
    /// 12 charts are renotation-table-derived, none of these are
    /// algorithmic placeholders).
    static let commonAustralianSoils: [MunsellSwatch] = [
        MunsellSwatch(value: "2", chroma: "1", hex: "#332927", name: "Black / Very dark brown", context: "High organic matter (A1 horizons)", hueTag: "10YR"),
        MunsellSwatch(value: "2", chroma: "2", hex: "#362B27", name: "Black / Very dark brown", context: "High organic matter (A1 horizons)", hueTag: "10YR"),
        MunsellSwatch(value: "3", chroma: "2", hex: "#553F31", name: "Dark brown", context: "Common topsoils", hueTag: "7.5YR"),
        MunsellSwatch(value: "3", chroma: "3", hex: "#533626", name: "Dark brown", context: "Common topsoils", hueTag: "10YR"),
        MunsellSwatch(value: "4", chroma: "3", hex: "#75573D", name: "Brown", context: "Very widespread", hueTag: "10YR"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#7D4F35", name: "Brown", context: "Very widespread", hueTag: "7.5YR"),
        MunsellSwatch(value: "5", chroma: "4", hex: "#937553", name: "Yellowish brown", context: "Weathered subsoils", hueTag: "10YR"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#9E7035", name: "Yellowish brown", context: "Weathered subsoils", hueTag: "10YR"),
        MunsellSwatch(value: "4", chroma: "4", hex: "#7F5040", name: "Reddish brown", context: "Iron-rich or moderately weathered", hueTag: "5YR"),
        MunsellSwatch(value: "3", chroma: "4", hex: "#5D3126", name: "Reddish brown", context: "Iron-rich or moderately weathered", hueTag: "5YR"),
        MunsellSwatch(value: "5", chroma: "6", hex: "#9F6C3F", name: "Strong brown", context: "Oxidised iron features", hueTag: "7.5YR"),
        MunsellSwatch(value: "5", chroma: "8", hex: "#A56623", name: "Strong brown", context: "Oxidised iron features", hueTag: "7.5YR"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#884534", name: "Red", context: "Lateritic / highly weathered soils", hueTag: "2.5YR"),
        MunsellSwatch(value: "4", chroma: "6", hex: "#8E483E", name: "Red", context: "Lateritic / highly weathered soils", hueTag: "10R"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#847977", name: "Grey / Light grey", context: "Bleached A2 or gleyed horizons", hueTag: "10YR"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#7E796D", name: "Grey / Light grey", context: "Bleached A2 or gleyed horizons", hueTag: "5Y"),
        MunsellSwatch(value: "5", chroma: "1", hex: "#777B6F", name: "Olive grey / Gley", context: "Reduced, waterlogged conditions", hueTag: "5GY"),
    ]
}